[package]
name = "obj-renderer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

wavefront_obj = "11.0.0"
rs-math3d = "0.9.24"
clap = { version = "4.5", features = ["derive"] }
image = "0.24"

[[bin]]
name = "obj-renderer-rust"
path = "src/main.rs"

[[bin]]
name = "roundabout_scene"
path = "src/roundabout_scene.rs"
